"""Async Python SDK for the onejudge CLI."""

from ._client import EventHandler, OneJudge
from ._errors import ContractError, OneJudgeProcessError, OneJudgeTimeoutError
from ._generated_types import (
    CandidateAttempt,
    EvalConfig,
    FailureDetail,
    FailureReport,
    FellThrough,
    HarnessAttribution,
    JudgeKind,
    JudgeVerdict,
    Message,
    NamedVerdict,
    ProviderConfig,
    ProviderKind,
    Role,
    RunConfig,
    RunReport,
    SpawnedProcess,
    StreamEvent,
    Telemetry,
    ToolEvent,
    Transcript,
    Usage,
    UserConfig,
)
from ._result import RunResult
from ._version import __version__

__all__ = [
    "CandidateAttempt",
    "ContractError",
    "EvalConfig",
    "EventHandler",
    "FailureDetail",
    "FailureReport",
    "FellThrough",
    "HarnessAttribution",
    "JudgeKind",
    "JudgeVerdict",
    "Message",
    "NamedVerdict",
    "OneJudge",
    "OneJudgeProcessError",
    "OneJudgeTimeoutError",
    "ProviderConfig",
    "ProviderKind",
    "Role",
    "RunConfig",
    "RunReport",
    "RunResult",
    "SpawnedProcess",
    "StreamEvent",
    "Telemetry",
    "ToolEvent",
    "Transcript",
    "Usage",
    "UserConfig",
    "__version__",
]
